collections:
  pages:
    output: true
    permalink: /:path/
    
  testimonials:
    output: true
    permalink: /testimonials/:name/
    
  team:
    output: true
    permalink: /team/:name/
    
  products:
    output: true
    permalink: /products/:name/
    
  events:
    output: true
    permalink: /events/:name/
    
  faqs:
    output: true
    permalink: /faq/:name/
    
  portfolio:
    output: true
    permalink: /portfolio/:slug/
    
  announcements:
    output: true
    permalink: /announcements/:slug/
    
defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "_portfolio"
      type: "portfolio"
    values:
      layout: "portfolio"
  - scope:
      path: "_announcements"
      type: "announcements"
    values:
      layout: "announcement" 