title: "Judwm's Blog"
description: "A personal blog about technology, programming, and personal development"
author: "Judwm"
logo: ""  # Add your logo path here if you have one

social:
  twitter: ""  # Your Twitter username
  github: "judwm"  # Your GitHub username
  linkedin: ""  # Your LinkedIn username
  instagram: ""  # Your Instagram username
