backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

css:
  - label: "Dark Theme"
    value: "dark"
    file: "admin/css/themes/dark.css"
  - label: "Minimal Theme"
    value: "minimal"
    file: "admin/css/themes/minimal.css"

# Fitur Tema Custom
theme:
  - label: "Tema Default"
    value: "default"
  - label: "Tema Gelap"
    value: "dark"
  - label: "Tema Minimalis"
    value: "minimal"

# Pengaturan Global
collections:
  - name: "global"
    label: "Pengaturan Global"
    editor:
      preview: false
    files:
      - name: "header_footer"
        label: "Header & Footer"
        file: "content/global/header-footer.md"
        fields:
          - { name: "site_title", label: "Judul Situs", widget: "string" }
          - { name: "logo", label: "Logo Situs", widget: "image", config: { media_library: { allow_multiple: false } } }
          - { name: "header_content", label: "Konten Header", widget: "markdown", required: false }
          - { name: "footer_content", label: "Konten Footer", widget: "markdown", required: false }
          - { name: "theme", label: "Tema Situs", widget: "select", options: ["default", "dark", "minimal"] }

  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Penulis", name: "author", widget: "string", default: "Admin" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Kategori", name: "category", widget: "select", options: ["Berita", "Tutorial", "Update"] }
      - { label: "Ringkasan", name: "excerpt", widget: "text" }
      - { label: "Konten", name: "body", widget: "markdown" }
      - label: "SEO Settings"
        name: "seo"
        widget: "object"
        fields:
          - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
          - { label: "Meta Description", name: "meta_description", widget: "text", required: false } 