backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

css:
  - label: "Dark Theme"
    value: "dark"
    file: "admin/css/themes/dark.css"
  - label: "Minimal Theme"
    value: "minimal"
    file: "admin/css/themes/minimal.css"

# Fitur Tema Custom
theme:
  - label: "Tema Default"
    value: "default"
  - label: "Tema Gelap"
    value: "dark"
  - label: "Tema Minimalis"
    value: "minimal"

# Pengaturan Global
collections:
  - name: "global"
    label: "Global Settings"
    editor:
      preview: false
    files:
      - name: "header_footer"
        label: "Header & Footer Settings"
        file: "_data/global/header-footer.yml"
        fields:
          - { name: "site_title", label: "Site Title", widget: "string" }
          - { name: "logo", label: "Site Logo", widget: "image", config: { media_library: { allow_multiple: false } } }
          - { name: "header_content", label: "Header Content", widget: "markdown", required: false }
          - { name: "footer_content", label: "Footer Content", widget: "markdown", required: false }
          - { name: "theme", label: "Site Theme", widget: "select", options: ["default", "dark", "minimal"] }

  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Penulis", name: "author", widget: "string", default: "Admin" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Kategori", name: "category", widget: "select", options: ["News", "Tutorial", "Update"] }
      - { label: "Ringkasan", name: "excerpt", widget: "text" }
      - { label: "Konten", name: "body", widget: "markdown" }
      - label: "SEO Settings"
        name: "seo"
        widget: "object"
        fields:
          - { label: "Meta Title", name: "meta_title", widget: "string", required: false }
          - { label: "Meta Description", name: "meta_description", widget: "text", required: false }

  - name: "pages"
    label: "Halaman Statis"
    folder: "_pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul Halaman", name: "title", widget: "string" }
      - { label: "Tata Letak", name: "layout", widget: "hidden", default: "page" }
      - { label: "Konten", name: "body", widget: "markdown" }
      - label: "Pengaturan Tambahan"
        name: "settings"
        widget: "object"
        fields:
          - { label: "Tampilkan di Menu", name: "show_in_menu", widget: "boolean", default: true }
          - { label: "Urutan Menu", name: "menu_order", widget: "number", default: 0 }

  - name: "seo_settings"
    label: "Pengaturan SEO"
    editor:
      preview: false
    files:
      - name: "global_seo"
        label: "SEO Global"
        file: "content/global/seo.md"
        fields:
          - { label: "Meta Description Default", name: "meta_description", widget: "text" }
          - { label: "Keywords", name: "keywords", widget: "list" }
          - { label: "Google Analytics ID", name: "ga_id", widget: "string", required: false }

  - name: "gallery"
    label: "Galeri"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul Gambar", name: "title", widget: "string" }
      - { label: "Gambar", name: "image", widget: "image" }
      - { label: "Kategori", name: "category", widget: "select", options: ["Portfolio", "Banner", "Clients"] }
      - { label: "Deskripsi", name: "description", widget: "text" }

  - name: "navigation"
    label: "Navigation Menu"
    editor:
      preview: false
    files:
      - name: "main_menu"
        label: "Main Menu"
        file: "_data/navigation.yml"
        fields:
          - label: "Menu Text"
            name: "menu_items"
            widget: "list"
            fields:
              - { label: "Teks Menu", name: "name", widget: "string" }
              - { label: "Link", name: "url", widget: "string" }
              - { label: "Open in New Tab", name: "new_tab", widget: "boolean", default: false }

  - name: "social_media"
    label: "Social Media"
    editor:
      preview: false
    files:
      - name: "social_links"
        label: "Social Media Links"
        file: "_data/social.yml"
        fields:
          - label: "Platform Name"
            name: "links"
            widget: "list"
            fields:
              - { label: "Nama Platform", name: "platform", widget: "string" }
              - { label: "URL Profil", name: "url", widget: "string" }
              - { label: "Ikon (Font Awesome)", name: "icon", widget: "string", hint: "Contoh: fa-facebook" }

  - name: "testimonials"
    label: "Testimonials"
    folder: "_testimonials"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Client Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Company", name: "company", widget: "string", required: false }
      - { label: "Avatar", name: "avatar", widget: "image", required: false }
      - { label: "Quote", name: "content", widget: "text" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }

  - name: "team"
    label: "Team Members"
    folder: "_team"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Full Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Photo", name: "photo", widget: "image" }
      - { label: "Bio", name: "content", widget: "markdown" }
      - label: "Social Links"
        name: "social"
        widget: "object"
        fields:
          - { label: "Twitter", name: "twitter", widget: "string", required: false }
          - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }

  - name: "products"
    label: "Products/Services"
    folder: "_products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Product Name", name: "title", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Price", name: "price", widget: "number", value_type: "float" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Category", name: "category", widget: "select", options: ["Physical", "Digital", "Service"] }
      - { label: "Featured Product", name: "featured", widget: "boolean", default: false }

  - name: "events"
    label: "Events"
    folder: "_events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Event Name", name: "title", widget: "string" }
      - { label: "Start Date", name: "start_date", widget: "datetime" }
      - { label: "End Date", name: "end_date", widget: "datetime", required: false }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Registration Link", name: "registration_url", widget: "string", required: false }
      - { label: "Event Details", name: "body", widget: "markdown" }

  - name: "faqs"
    label: "FAQs"
    folder: "_faqs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Question", name: "question", widget: "string" }
      - { label: "Answer", name: "answer", widget: "markdown" }
      - { label: "Category", name: "category", widget: "select", options: ["General", "Payment", "Technical"] } 